Source/Source/Controllers/Menu_ListLSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Source.Areas.Admin.Controllers;
using DAO;
    

namespace Source.Controllers
{
    public class Menu_ListLSPController : BaseController
    {
        // GET: Menu_ListLSP
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuPartial()
        {
            List<LoaiSanPhamDAO> lstLSP = LoaiSanPham_Service.GetAll();
            return PartialView(lstLSP);
        }
    }
}

Source/Source/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;
using Source.Areas.Admin.Controllers;

namespace Source.Controllers
{
    public class SanPhamController : BaseController
    {
        // GET: MenuProduct
        public ActionResult LoaiSanPham()
        {
            List<LoaiSanPhamDAO> lstLSP = LoaiSanPham_Service.GetAll();
            return View(lstLSP);
        }
        public ActionResult SanPham()
        {
            return View();
        }
        public PartialViewResult _SanPham(int MaLoaiSanPham)
        {
            List<SanPham_LoaiSanPham> lstSP = SanPham_Service.SP_GetAllBy(MaLoaiSanPham);
            List<Combo_SanPham> lstCB = Combo_Service.CB_GetAllBy(MaLoaiSanPham);
            TempData["sanPham"] = lstSP;
            TempData["comBo"] = lstCB;
            return PartialView();
        }

        public PartialViewResult SanPham_ChiTiet(int MaMatHang, bool laSanPham)
        {
            if (laSanPham == false)
            {
                Combo_SanPham sp_cb = Combo_Service.SelectByPrimaryKey(MaMatHang);
                ViewBag.cbdetail = sp_cb;
            }
            else
            {
                SanPhamDAO sp = SanPham_Service.GetByID(MaMatHang);              
                ViewBag.spdetail = sp;
            }
            return PartialView();
       }
        public PartialViewResult _KhuyenMai()
        {
            List<KhuyenMaiDAO> lstKM = KhuyenMai_Service.GetAll();
            return PartialView(lstKM);
        }
    }
}

Source/Source/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;
using Source.Areas.Admin.Controllers;

namespace Source.Controllers
{
    public class TimKiemController : BaseController
    {
        // GET: TimKiem
        public ActionResult KQTimKiem(string sTuKhoa)
        {
            var lstSP = SanPham_Service.SelectBy(sTuKhoa);
            return View(lstSP);
        }
    }
}

Source/Source/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="bootstrap material admin template">
    <meta name="author" content="">
    <title>Fast Food</title>
    <link rel="apple-touch-icon" href="~/Assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="~/favicon.ico">
    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/Assets/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/global/css/bootstrap-extend.min.css">
    <link rel="stylesheet" href="~/Assets/css/site.min.css">
    <!-- Plugins -->
    <link rel="stylesheet" href="~/Assets/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="~/Assets/global/vendor/waves/waves.css">
    <link rel="stylesheet" href="~/Assets/examples/css/pages/login.css">

    <!-- Fonts -->
    <link rel="stylesheet" href="~/Assets/global/fonts/material-design/material-design.min.css">
    <link rel="stylesheet" href="~/Assets/global/fonts/brand-icons/brand-icons.min.css">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    <!--[if lt IE 9]>
    <script src="~/Assets/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    <!--[if lt IE 10]>
    <script src="~/Assets/global/vendor/media-match/media.match.min.js"></script>
    <script src="~/Assets/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    <!-- Scripts -->
    <script src="~/Assets/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
</head>
<body class="animsition page-login layout-full page-dark">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Page -->
    <div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">
        >
        <div class="page-content vertical-align-middle">
            <div class="brand">
                <img class="brand-img" src="~/Assets//images/logo.png" alt="...">
            </div>
            @RenderBody()
            <footer class="page-copyright page-copyright-inverse">
                <p>WEBSITE BY Creation Studio</p>
                <p>© 2018. All RIGHT RESERVED.</p>
                <div class="social">
                    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                        <i class="icon bd-twitter" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                        <i class="icon bd-facebook" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                        <i class="icon bd-google-plus" aria-hidden="true"></i>
                    </a>
                </div>
            </footer>
        </div>
    </div>
    <!-- End Page -->
    <!-- Core  -->
    <script src="~/Assets/global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
    <script src="~/Assets/global/vendor/jquery/jquery.js"></script>
    <script src="~/Assets/global/vendor/popper-js/umd/popper.min.js"></script>
    <script src="~/Assets/global/vendor/bootstrap/bootstrap.js"></script>
    <script src="~/Assets/global/vendor/animsition/animsition.js"></script>
    <script src="~/Assets/global/vendor/mousewheel/jquery.mousewheel.js"></script>
    <script src="~/Assets/global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
    <script src="~/Assets/global/vendor/asscrollable/jquery-asScrollable.js"></script>
    <script src="~/Assets/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
    <script src="~/Assets/global/vendor/waves/waves.js"></script>
    <!-- Scripts -->
    <script src="~/Assets/global/js/Component.js"></script>
    <script src="~/Assets/global/js/Plugin.js"></script>
    <script src="~/Assets/global/js/Base.js"></script>
    <script src="~/Assets/global/js/Config.js"></script>
    <script src="~/Assets/js/Section/Menubar.js"></script>
    <script src="~/Assets/js/Section/GridMenu.js"></script>
    <script src="~/Assets/js/Section/Sidebar.js"></script>
    <script src="~/Assets/js/Section/PageAside.js"></script>
    <script src="~/Assets/js/Plugin/menu.js"></script>
    <script src="~/Assets/global/js/config/colors.js"></script>
    <script src="~/Assets/js/config/tour.js"></script>
    <script>Config.set('assets', '~/Assets');</script>
    <!-- Page -->
    <script src="~/Assets/js/Site.js"></script>
    <script src="~/Assets/global/js/Plugin/asscrollable.js"></script>
    <script src="~/Assets/global/js/Plugin/slidepanel.js"></script>
    <script src="~/Assets/global/js/Plugin/switchery.js"></script>
    <script src="~/Assets/global/js/Plugin/jquery-placeholder.js"></script>
    <script src="~/Assets/global/js/Plugin/material.js"></script>
    <script src="~/Scripts/Features.js"></script>

    <script>
        $(document).ready(function () {
            setTimeout(() => {
                $("#txtName,#txtPassword").keyup();

            },0)
        });
      (function(document, window, $){
        'use strict';

        var Site = window.Site;
        $(document).ready(function(){
          Site.run();
        });
      })(document, window, jQuery);
    </script>
</body>
</html>

Source/Source/Views/Shared/_Layout.cshtml
@{
    DAO.TaiKhoanDAO user = (DAO.TaiKhoanDAO)Session["User"];
}
<!DOCTYPE html>
<html>
<head>
    <title>FastFood Việt Nam</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Assets/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/css/layout.css">
    <link rel="stylesheet" href="~/Assets/css/font-awesome.css">
    <link rel="stylesheet" href="~/Assets/css/product.css">
    <link rel="stylesheet" href="~/Assets/css/menu-product.css">
    <link rel="stylesheet" href="~/Assets/css/product.css">
    <link rel="stylesheet" href="~/Assets/css/introduce.css" />
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</head>
<body>
    @*@using (Html.BeginForm("KQTimKiem","TimKiem"))
        {
            <input type="text" name="sTuKhoa" placeholder="nhapj tu khoa" />
            <button type="submit">tim kiem</button>
        }*@
    <div class="header">
        <div class="headertop-right">
            <ul>
                @if (user == null)
                {
                    <li>
                        <a href="@Url.Action("Login", "Auth")">Đăng Nhập</a>
                    </li>
                    <img src="~/Assets/images/topbar.png">
                    <li style="margin-right: 3px">
                        <a href="@Url.Action("Register","Auth")">Đăng Kí</a>
                    </li>
                }
                else
                {

                    <li>
                        <a href="#" style="margin-right: 1%;display: contents">Xin Chào, @user.TenTaiKhoan</a>
                    </li>
                    <img src="~/Assets/images/topbar.png">
                    <li><a href="@Url.Action("Logout","Auth")">Đăng Xuất</a></li>
                }
            </ul>
        </div>
        <div class="container">
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="~/Assets/images/logo.png"></a>
            </div>
            @Html.Action("MenuPartial", "Menu_ListLSP")
        </div>
    </div>
    @RenderBody()
    <div class="footer">
        <div class="container ">
            <div style="text-align: center; padding-top:10px; padding-bottom: 10px;">
                <h4>Kết nối với chúng tôi</h4>
                <ul class="social ">
                    <li><a href="# "><i> </i></a></li>
                    <li><a href="# "><i class="twitter "> </i></a></li>
                    <li><a href="# "><i class="rss "> </i></a></li>
                    <li><a href="# "><i class="gmail "> </i></a></li>
                </ul>
            </div>
        </div>
        <div class="clearfix"> </div>
        <div class="footer-class ">
            <p>
                FastFood WebSite | Design by HungNT
                <a href="#" class="backtop backtop-visible"></a>
            </p>
        </div>
    </div>
    <div class="modal fade" id="cart" tabindex="-1" role="dialog" aria-labelledby="cart" aria-hidden="true">
        <div class="modal-dialog modal-dialog" role="document" style="max-width: none;width:auto;padding-left: 3%;padding-right: 3%;">
            <div class="modal-content">
                <div class="modal-header" style="font-weight: bold;color: #ffffff;background-color: #EF5F21;padding: 5px 5px 5px">
                    <h5 style="font-weight: bold;color: antiquewhite; font-size: 25px; margin-left: 2%" class="modal-title">Phần Ăn Bạn Đã Chọn</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-right:0; font-size:40px">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body-gh" style="overflow-x: scroll;">
                    <div class="container" style="max-height: 400px">
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="~/Assets/global/vendor/jquery/jquery.js"></script>
<script src="~/Assets/global/vendor/popper-js/umd/popper.min.j"></script>
<script src="~/Assets/global/vendor/bootstrap/bootstrap.js"></script>
<script src="~/Assets/js/App/website.js"></script>
<script src="~/Scripts/Features.js"></script>
<script>
    $(window).scroll(function () {
        if ($(window).scrollTop() == 0) {
            $(".header").css("position", "relative");
        } else {
            $(".header").css("position", "fixed");
        }
    });
</script>
</html>

Source/Source/Views/Shared/_layoutSanPham.cshtml
@{
    ViewBag.Title = "_layoutSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="content">
        @RenderBody()

        <div class="content-bottom">
            <div class="title-menu">
                <h4>Khuyễn Mãi Hiện Có</h4>
            </div>
            @Html.Action("_KhuyenMai", "SanPham")
        </div>
    
        <div class="modal fade" id="showdetail" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header" style="font-weight: bold;color: black;background-color: gainsboro;padding: 5px 5px 5px">
                        <h5 class="modal-title" id="exampleModalScrollableTitle">Thay đổi chi tiết phần ăn</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            @{
                                Html.RenderAction("SanPham_ChiTiet", "SanPham", new { MaMatHang = 1, laSanPham = true });
                            }
                        </div>
                    </div>
                    @*<div class="modal-footer">
                        <button data-toggle="modal" data-target="#cart" type="button" class="add-to-cart" data-dismiss="modal" onclick="getsp(MaMatHang, laSanPham)">Thêm vào giỏ hàng</button>
                        <button type="button" class="payment">Thanh Toán</button>
                    </div>*@
                </div>
            </div>
        </div>   
    </div>
</div>