Source/Source/Areas/Admin/Controllers/DonHangController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Source.Areas.Admin.Controllers
{
    public class DonHangController : BaseController
    {
        // GET: Admin/DonHang
        public ActionResult DanhSach()
        {
            return View();
        }
        public PartialViewResult _DanhSach(int pageNumber = 1, int pageSize = 10, string keyText = "")
        {
            List<DonHangDAO> list = new List<DonHangDAO>();
            try
            {
                int totalEntries;
                list = DonHang_Service.GetAllBy(pageNumber, pageSize, keyText, out totalEntries);
                ViewBag.maxNumber = Math.Ceiling(totalEntries / (double)pageSize);
                ViewBag.pageNumber = pageNumber;
                ViewBag.pageSize = pageSize;
            }
            catch (Exception e)
            {
                throw e;
            }
            return PartialView(list);
        }
    }
}

Source/Source/Areas/Admin/Views/DonHang/DanhSach.cshtml
@{
    ViewBag.Title = "DanhSach";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="page-header">
    <h1 class="page-title">Danh Sách Đơn Hàng</h1>
    <div class="page-header-actions">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Index">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Đơn Hàng</a></li>
            <li class="breadcrumb-item active">Danh Sách Đơn Hàng</li>
        </ol>
    </div>
</div>
<div class="page-content">
    <!-- Panel -->
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="dataTables_length" id="DataTables_Table_0_length">
                        <label>
                            <select name="DataTables_Table_0_length" onchange="changePage(1)" id="pageSize" aria-controls="DataTables_Table_0" class="form-control form-control-sm">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                            </select>
                        </label>
                    </div>
                </div>
                <div class="col-sm-12 col-md-5">
                    <div id="DataTables_Table_0_filter" class="dataTables_filter">
                        <label>
                            <input type="text" id="txtSearch" style="padding-right:0;" class="form-control form-control-sm" placeholder="Tìm kiếm " aria-controls="DataTables_Table_0">
                        </label>
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div id="DataTables_Table_0_filter" class="dataTables_filter">
                        <button type="button" class="btn btn-block btn-sm btn-primary waves-effect waves-classic" onclick="changePage(1)"><i class="icon wb-search" aria-hidden="true"></i></button>
                    </div>
                </div>

            </div>
            <div class="row row-lg">
                <div class="col-lg data-table">
                    @{Html.RenderAction("_DanhSach", "DonHang");}
                </div>
            </div>
        </div>
    </div>
    <!-- End Panel -->
</div>
<!-- End Page -->
<!-- Modal -->
<div class="modal fade modal-3d-flip-vertical" id="info-modal" aria-hidden="true"
     aria-labelledby="exampleModalTitle" role="dialog">
    <div class="modal-dialog modal-simple">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thông tin</h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-pure" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" onclick="saveProduct()">Gửi</button>
            </div>
        </div>
    </div>
</div>
<script>
    var url_GetTb = '/Admin/DonHang/_DanhSach';
</script>

Source/Source/Areas/Admin/Views/DonHang/_DanhSach.cshtml
@model List<DAO.DonHangDAO>

@{
    int pageFrom = ((ViewBag.pageNumber - 1) * ViewBag.pageSize) + 1;

}
<!-- Table -->
<div class="example-wrap">
    <div class="example table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>STT</th>
                    <th class="text-center">Mã hóa đơn</th>
                    <th class="text-center" width="300">Đơn giá</th>
                    <th>Địa chỉ</th>
                    <th class="text-center">Thời gian</th>
                    <th class="text-center" width="150">Trạng thái</th>
                    <th class="text-center" width="180">Chỉnh sửa</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>@(pageFrom + i)</td>
                            <td class="text-center" width="130">@Model[i].MaHoaDon</td>
                            <td class="text-center money">@Model[i].TongTien.ToString().Replace(".00","")</td>
                            <td width="300">@Model[i].DiaChi</td>
                            <td width="200">@Model[i].ThoiGian</td>
                            <td width="150" class="text-center">@Model[i].TrangThai</td>
                            <td class="text-center">
                                <i class="icon wb-check text-success" title="Xử lí" onclick="updateInvoice(this,0)" data-id='@Model[i].MaHoaDon' style="margin-right:5px;"></i>
                                <i class="icon wb-refresh text-primary" title="Đang xử lí" onclick="updateInvoice(this,1)" data-id='@Model[i].MaHoaDon' style="margin-right:5px;"></i>
                                <i class="icon wb-close text-danger" title="Hủy" onclick="updateInvoice(this,2)" data-id='@Model[i].MaHoaDon'></i>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="text-center" colspan="7">Không có dữ liệu</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<!-- End Table -->
@{ Html.RenderAction("_Pagination", "Home", new { maxNumber = ViewBag.maxNumber, pageNumber = ViewBag.pageNumber });}

<script>
    $(".money").each(function () {
        formatTableCurrency(this);
    })

    function updateInvoice(element, status) {
        // 0: Xử lí
        // 1: Đang xử lí
        // 2 Hủy
        const res = confirm("Bạn có muốn đổi trạng thái hóa đơn");
        if (res) {
            let value = "";
            if (status === 0) {
                value = "Xử lí";
            } else if (status === 1) {
                value = "Đang xử lí";
            } else {
                value = "Hủy";
            }
            $.ajax({
                url: '/Ajax/UpdateInvoiceStatus',
                method: 'post',
                data: {
                    ID: +element.getAttribute('data-id'),
                    value: value
                }
            }).done((result) => {
                alertMess(result);
            })
        }
        
    }
</script>