Source/Source/Areas/Admin/Controllers/KhuyenMaiController.cs
using DAO;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Source.Areas.Admin.Controllers
{
    public class KhuyenMaiController : BaseController
    {
        // GET: Admin/KhuyenMai
        public ActionResult DanhSach()
        {
            TempData.Clear();
            return View();
        }
        public PartialViewResult _DanhSach(int pageNumber = 1, int pageSize = 10, string keyText = "")
        {
            List<KhuyenMaiDAO> list = new List<KhuyenMaiDAO>();
            try
            {
                int totalEntries;
                list = KhuyenMai_Service.GetAllBy(pageNumber, pageSize, keyText, out totalEntries);
                ViewBag.maxNumber = Math.Ceiling(totalEntries / (double)pageSize);
                ViewBag.pageNumber = pageNumber;
                ViewBag.pageSize = pageSize;
                TempData["promotions"] = list;
                TempData.Keep();
            }
            catch (Exception e)
            {
                throw e;
            }
            return PartialView(list);
        }
        public PartialViewResult _KhuyenMai_ChiTiet(int ID)
        {
            List<KhuyenMaiDAO> promotions = (List<KhuyenMaiDAO>)TempData["promotions"];
            TempData.Keep();
            KhuyenMaiDAO promotion = promotions.Where(x => x.MaKhuyenMai.Equals(ID)).FirstOrDefault();
            if (promotion == null)
            {
                promotion = new KhuyenMaiDAO();
                promotion.ThoiGianBatDau = DateTime.Now;
                promotion.ThoiGianKetThuc = DateTime.Now;
            }
            return PartialView(promotion);
        }

    }
}

Source/Source/Areas/Admin/Views/KhuyenMai/DanhSach.cshtml
@{
    ViewBag.Title = "Khuyến mãi";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1 class="page-title">Danh Sách Sản phẩm</h1>
    <div class="page-header-actions">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Index">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Khuyến mãi</a></li>
            <li class="breadcrumb-item active">Danh Sách</li>
        </ol>
    </div>
</div>

<div class="page-content">
    <!-- Panel -->
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="dataTables_length" id="DataTables_Table_0_length">
                        <label>
                            <select name="DataTables_Table_0_length" onchange="changePage(1)" id="pageSize" aria-controls="DataTables_Table_0" class="form-control form-control-sm">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                            </select>
                        </label>
                    </div>
                </div>
                <div class="col-sm-12 col-md-5">
                    <div id="DataTables_Table_0_filter" class="dataTables_filter">
                        <label>
                            <input type="text" id="txtSearch" style="padding-right:0;" class="form-control form-control-sm" placeholder="Tìm kiếm " aria-controls="DataTables_Table_0">
                        </label>
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div id="DataTables_Table_0_filter" class="dataTables_filter">
                        <button type="button" class="btn btn-block btn-sm btn-primary waves-effect waves-classic" onclick="changePage(1)"><i class="icon wb-search" aria-hidden="true"></i></button>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-12 d-flex justify-content-end">
                    <button class="btn btn-primary" onclick="setValueForModal(this,false)" data-id='0' data-target="#info-modal" data-toggle="modal" aria-hidden="true">Thêm mới</button>
                </div>
            </div>
            <div class="row row-lg">
                <div class="col-lg data-table">
                    @{Html.RenderAction("_DanhSach", "KhuyenMai");}
                </div>
            </div>
        </div>
    </div>
    <!-- End Panel -->

</div>
<!-- End Page -->
<!-- Modal -->
<div class="modal fade modal-3d-flip-vertical" id="info-modal" aria-hidden="true"
     aria-labelledby="exampleModalTitle" role="dialog">
    <div class="modal-dialog modal-simple">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thông tin</h4>
            </div>
            <div class="modal-body">
                @{Html.RenderAction("_KhuyenMai_ChiTiet", "KhuyenMai", new { ID = -1 });}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-pure" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" onclick="saveProduct()">Gửi</button>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

<script>
    var path = '';
    var url_GetTb = '/Admin/KhuyenMai/_DanhSach';
    var url_GetMd = '/Admin/KhuyenMai/_KhuyenMai_ChiTiet';
    var url_InsertUpdate = '/Admin/Ajax/addOrUpdatePromotion';
    function saveProduct() {
        const start = $("#ThoiGianBatDau").val().split("/").reverse().join("/");
        const end = $("#ThoiGianKetThuc").val().split("/").reverse().join("/");

    if (new Date(start) > new Date(end)) {
        return toastr.error("Thời gian bắt đầu không được lớn hơn thời gian kết thúc");
    }
        const obj = getValueFromModal();
        if (!obj) { return; }

        if (!file && !obj.HinhAnh) { // file có thể null
            return toastr.error('Vui lòng chọn hình ảnh');
        }
        if (file) {
            const formData = new FormData();
            formData.append('file', file);
            $.ajax({
                method: 'post',
                url: '/Admin/Ajax/UploadFile',
                data: formData,
                "async": false,
                "contentType": false,
                "processData": false
            }).done(result => {
                if (result.Data.Code == 0) {
                    obj.HinhAnh = result.Data.Message;
                } else {
                    $("#HinhAnh").val('');
                    return toastr.error(result.Data.Message);
                }
            });
        }
        insertOrUpdate(obj);

    }
</script>

Source/Source/Areas/Admin/Views/KhuyenMai/_DanhSach.cshtml
@model List<DAO.KhuyenMaiDAO>
@using Source.Configuration

@{
    int pageFrom = ((ViewBag.pageNumber - 1) * ViewBag.pageSize) + 1;

}
<!-- Table -->
<div class="example-wrap">
    <div class="example table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên khuyến mãi</th>
                    <th>Thời gian bắt đầu</th>
                    <th>Thời gian kết thúc</th>
                    <th>Chiết khấu</th>
                    <th class="text-center">Hình ảnh</th>
                    <th class="text-center">Chỉnh sửa</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>@(pageFrom + i)</td>
                            <td>@Model[i].TenKhuyenMai</td>
                            <td>@Model[i].ThoiGianBatDau.ToString("dd/M/yyyy")</td>
                            <td>@Model[i].ThoiGianKetThuc.ToString("dd/M/yyyy")</td>
                            <td>@Model[i].ChietKhau</td>
                            <td class="text-center"><img width="150px" height="150px" @if (!string.IsNullOrEmpty(@Model[i].HinhAnh)) { <text> src=@Url.Content(AppConfig.uploadFolder + Model[i].HinhAnh) </text>  } alt="" /></td>
                            <td class="text-center">
                                <i class="icon wb-edit text-primary" onclick="setValueForModal(this,true)" data-id='@Model[i].MaKhuyenMai' data-target="#info-modal" data-toggle="modal" aria-hidden="true"></i>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="text-center" colspan="7">Không có dữ liệu</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
<!-- End Table -->
@{ Html.RenderAction("_Pagination", "Home", new { maxNumber = ViewBag.maxNumber, pageNumber = ViewBag.pageNumber });}

Source/Source/Areas/Admin/Views/KhuyenMai/_KhuyenMai_ChiTiet.cshtml
@model DAO.KhuyenMaiDAO
@using Source.Configuration
@using DAO;


<div class="panel-body container-fluid">
    <form autocomplete="off">
        <input type="hidden" value='@Model.MaKhuyenMai' id="MaKhuyenMai" name="inputText" placeholder="Text" />
        <div class="form-group form-material" data-plugin="formMaterial">
            <label class="form-control-label" for="TenKhuyenMai">Tên Khuyến Mãi *</label>
            <input type="text" class="form-control required" value='@Model.TenKhuyenMai' id="TenKhuyenMai" />
        </div>

        <div class="form-group form-material" data-plugin="formMaterial">
            <label class="form-control-label" for="ThoiGianBatDau">Thời gian bắt đầu *</label>
            <input type="text" class="form-control datepicker required" readonly value='@Model.ThoiGianBatDau.ToString("dd/M/yyyy")' id="ThoiGianBatDau" data-plugin="datepicker"/>

        </div>
        <div class="form-group form-material" data-plugin="formMaterial">
            <label class="form-control-label" for="ThoiGianKetThuc">Thời gian kết thúc *</label>
            <input type="text" class="form-control datepicker required" readonly value='@Model.ThoiGianKetThuc.ToString("dd/M/yyyy")' id="ThoiGianKetThuc" data-plugin="datepicker"/>
        </div>
        <div class="form-group form-material" data-plugin="formMaterial">
            <label class="form-control-label" for="ChietKhau">Chiết khấu *</label>
            <input type="number" class="form-control percent required" value='@Model.ChietKhau' id="ChietKhau" />
        </div>

        <div class="form-group" data-plugin="formMaterial">
            <label class="form-control-label font-weight-bold" for="HinhAnh">Hình ảnh *</label>
            <input type="file" id="file">
            <input type="hidden" value="@Model.HinhAnh" id="HinhAnh">
            <br>
            <img @if (!string.IsNullOrEmpty(@Model.HinhAnh)) { <text> src=@AppConfig.uploadFolder@Model.HinhAnh</text> } width='200px' height='200px' id="showImg" style='@if (Model.MaKhuyenMai.Equals(0)) { <text>display:none;</text> } else { <text>display:block;</text> } ' )>
        </div>

    </form>
</div>
<script>
    var file=undefined;
    $(document).ready(function () {
        $("#ThoiGianBatDau,#ThoiGianKetThuc").datepicker({ format: 'dd/mm/yyyy'});
    })
    $("#file").change(function (event) {
        $("#showImg").css("display", "none");
        if (event.target.files) {
            file = event.target.files[0];
            //const allowedExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
              if (!file.type.includes('image')) {
                  this.value = '';
                  file = undefined;
                  toastr.error('Vui lòng chọn file ảnh');
                return;
              }
          if (file.size / 1024 / 1024 >= 8) {
              this.value = '';
              file = undefined;
              toastr.error('Dung lượng file không được vượt quá 8MB')
            return;
          }
            const fd = new FileReader();
            fd.readAsDataURL(file);
            fd.onload = (result) => {
                $("#showImg").attr("src", result.target.result);
                $("#showImg").css("display", "block");
            }
        }
    });

</script>