Source/Source/Controllers/GioiThieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Source.Controllers
{
    public class GioiThieuController : Controller
    {
        // GET: GioiThieu
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/Source/Controllers/Menu_ListLSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Source.Areas.Admin.Controllers;
using DAO;
    

namespace Source.Controllers
{
    public class Menu_ListLSPController : BaseController
    {
        // GET: Menu_ListLSP
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuPartial()
        {
            List<LoaiSanPhamDAO> lstLSP = LoaiSanPham_Service.GetAll();
            return PartialView(lstLSP);
        }
    }
}

Source/Source/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;
using Source.Areas.Admin.Controllers;

namespace Source.Controllers
{
    public class SanPhamController : BaseController
    {
        // GET: MenuProduct
        public ActionResult LoaiSanPham()
        {
            List<LoaiSanPhamDAO> lstLSP = LoaiSanPham_Service.GetAll();
            return View(lstLSP);
        }
        public ActionResult SanPham()
        {
            return View();
        }
        public PartialViewResult _SanPham(int MaLoaiSanPham)
        {
            List<SanPham_LoaiSanPham> lstSP = SanPham_Service.SP_GetAllBy(MaLoaiSanPham);
            List<Combo_SanPham> lstCB = Combo_Service.CB_GetAllBy(MaLoaiSanPham);
            TempData["sanPham"] = lstSP;
            TempData["comBo"] = lstCB;
            return PartialView();
        }

        public PartialViewResult SanPham_ChiTiet(int MaMatHang, bool laSanPham)
        {
            if (laSanPham == false)
            {
                Combo_SanPham sp_cb = Combo_Service.SelectByPrimaryKey(MaMatHang);
                ViewBag.cbdetail = sp_cb;
            }
            else
            {
                SanPhamDAO sp = SanPham_Service.GetByID(MaMatHang);              
                ViewBag.spdetail = sp;
            }
            return PartialView();
       }
        public PartialViewResult _KhuyenMai()
        {
            List<KhuyenMaiDAO> lstKM = KhuyenMai_Service.GetAll();
            return PartialView(lstKM);
        }
    }
}

Source/Source/Views/Menu_ListLSP/MenuPartial.cshtml
@model List<DAO.LoaiSanPhamDAO>

<div class="menu">
    <div class="listmenu">
        <ul>
            <li>
                <a href="#">Khuyễn Mãi</a>
            </li>
            <img src="~/Assets/images/topbar-separator.png">
            <li>
                <a href="@Url.Action("LoaiSanPham","SanPham")">Thực Đơn</a>
                <div class="memenu">
                    <ul>
                        @foreach(var item in Model)
                        {
                            <li>
                                <a href="@Url.Action("SanPham","SanPham", new {@MaLoaiSanPham = @item.MaLoaiSanPham})">@item.TenLoaiSanPham</a>
                            </li>
                        }
                    </ul>
                    
                </div>
            </li>
            <img src="~/Assets/images/topbar-separator.png">
            <li>
                <a href="#">Chi Nhánh</a>
            </li>
            <img src="~/Assets/images/topbar-separator.png">
            <li>
                <a href="@Url.Action("Index","GioiThieu")">Giới Thiệu</a>
            </li>
            <img src="~/Assets/images/topbar-separator.png">
            <li>
                <button data-toggle="modal" data-target="#cart" onclick="XemGioHang()" ><img src="~/Assets/images/cart.png"> Giỏ Hàng</button>
            </li>
        </ul>
    </div>
</div>
<script>
    function XemGioHang() {
        $.ajax({
            url: '/GioHang/GioHang_ChiTiet'
        }).done((result) => {
            $(".modal-body-gh .container").html(result);
        })
    }
</script>